
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_datawarehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'user'


# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start: "GRANT SELECT ON ALL TABLES IN SCHEMA public,store,matomo,stripe,fulfillrite TO analytics;"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_datawarehouse:

    store:
      +tags:
        - "store"
        - "matomo"
        - "stripe"
      +materialized: view
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"

    matomo:
      +tags:
        - "matomo"
      +materialized: table
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"

    stripe:
      +tags:
        #- "store"
        - "stripe"
        #- "matomo"
      +materialized: view
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"

    facebook:
      +enabled: true
      +tags:
        - "facebook"
      +materialized: table
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"

    profitability:
      +enabled: true
      +tags:
        - "stripe"
        - "store"
        - "matomo"
        - "facebook"
      +materialized: table
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"

    exchange_rates:
      +enabled: true
      +tags:
        - "exchange_rates"
      +materialized: view
      +post-hook: "GRANT SELECT ON {{ this }} TO analytics;"
