SELECT
  d.id,
  d.reason,
  d.status AS dispute_status,
  TO_TIMESTAMP(d.created::BIGINT) AS date_created,
  ROUND(d.amount::NUMERIC/100,2) AS disputed_amount,
  d.currency,
  d.evidence::jsonb->>'receipt' AS receipt,
  d.evidence::jsonb->>'customer_name' AS customer_name,
  d.evidence::jsonb->>'shipping_date' AS shipping_date,
  d.evidence::jsonb->>'shipping_carrier' AS shipping_carrier,
  d.evidence::jsonb->>'shipping_tracking_number' AS shipping_tracking_number,
  d.evidence::jsonb->>'customer_purchase_ip' AS customer_purchase_ip,
  d.evidence::jsonb->>'customer_email_address' AS customer_email_address,
  d.evidence::jsonb->>'uncategorized_file' AS uncategorized_file,
  d.evidence::jsonb->>'shipping_documentation' AS shipping_documentation,
  TO_TIMESTAMP((d.evidence_details::jsonb->>'due_by')::BIGINT) AS due_by,
  d.evidence_details::jsonb->>'pass_due' AS pass_due,
  d.evidence_details::jsonb->>'has_evidence' AS has_evidence,
  d.evidence_details::jsonb->>'submission_count' AS submission_count,
  ROUND(((d.balance_transactions::jsonb->>0)::jsonb->>'fee')::NUMERIC/100,2) AS fee,
  ROUND(((d.balance_transactions::jsonb->>0)::jsonb->>'net')::NUMERIC/100,2) AS net,
  o.order_no,
  o.status AS order_status,
  o.order_currency,
  o.payment_method_title,
  o.billing_first_name,
  o.billing_last_name,
  o.billing_address_1,
  o.billing_city,
  o.billing_state,
  o.billing_postcode,
  o.billing_country,
  o.shipping_first_name,
  o.shipping_last_name,
  o.shipping_address_1,
  o.shipping_city,
  o.shipping_state,
  o.shipping_postcode,
  o.shipping_country
FROM stripe.disputes AS d
LEFT JOIN {{ref('an_stripe')}} AS s ON d.id = s.dispute
LEFT JOIN {{ref('an_orders_complete')}} AS o ON s.id = o.transaction_id
