SELECT
  matomo_log_conversion.idsite::INT,
  ENCODE(DECODE(matomo_log_conversion.idvisitor,'base64'),'hex')::TEXT AS idvisitor, -- HEX type in mysql
  matomo_log_conversion.idvisit::BIGINT,
  matomo_log_conversion.idlink_va::BIGINT,
  matomo_log_conversion.idgoal::INT,
  CAST(matomo_log_conversion.idorder AS INT) AS order_no,
  matomo_log_visit.visit_first_action_time::TIMESTAMP AS visit_first_action_time,
  matomo_log_visit.visit_last_action_time::TIMESTAMP AS visit_last_action_time,
  matomo_log_conversion.url::TEXT,
  matomo_log_conversion.items::SMALLINT,
  CAST(matomo_log_conversion.buster AS BIGINT), -- INT out of range, use BIGINT
  matomo_log_conversion.revenue::FLOAT,
  matomo_log_conversion.revenue_discount::FLOAT,
  matomo_log_conversion.revenue_shipping::FLOAT,
  matomo_log_conversion.revenue_subtotal::FLOAT,
  matomo_log_conversion.revenue_tax::FLOAT,
  matomo_log_conversion.server_time::TIMESTAMP AS server_time,
  matomo_log_conversion.idaction_url::INT,
  COALESCE(matomo_log_conversion.campaign_source::TEXT,'untracked') AS mtm_source,
  COALESCE(matomo_log_conversion.campaign_medium::TEXT,'untracked') AS mtm_medium,
  COALESCE(matomo_log_conversion.campaign_name::TEXT,'untracked') AS mtm_campaign,
  COALESCE(matomo_log_conversion.campaign_content::TEXT,'untracked') AS mtm_content,
  COALESCE(matomo_log_conversion.campaign_keyword::TEXT,'untracked') AS mtm_kwd,
  COALESCE(matomo_log_conversion.campaign_id::TEXT,'untracked') AS mtm_cid,
  COALESCE(matomo_log_conversion.campaign_group::TEXT,'untracked') AS mtm_group,
  COALESCE(matomo_log_conversion.campaign_placement::TEXT,'untracked') AS mtm_placement,
  '0.0.0.0'::inet + ('x' || lpad(ENCODE(DECODE(matomo_log_visit.location_ip,'base64'),'hex'), 8, '0'))::bit(32)::bigint AS location_ip, -- INET type, i am a smartboi
  matomo_log_conversion.location_city::TEXT,
  matomo_log_conversion.location_region::TEXT,
  matomo_log_conversion.location_country::TEXT,
  matomo_log_visit.location_latitude::NUMERIC,
  matomo_log_visit.location_longitude::NUMERIC,
  matomo_log_conversion.referer_name::TEXT,
  matomo_log_conversion.referer_type::SMALLINT,
  matomo_log_conversion.referer_keyword::TEXT,
  matomo_log_visit.referer_url::TEXT,
  matomo_log_visit.visitor_returning::BOOLEAN,
  matomo_log_visit.config_client_type::BOOLEAN,
  matomo_log_visit.config_device_type::SMALLINT,
  matomo_log_visit.custom_dimension_1::TEXT,
  matomo_log_visit.custom_dimension_2::TEXT,
  matomo_log_visit.custom_dimension_3::TEXT,
  matomo_log_visit.custom_dimension_4::TEXT,
  matomo_log_visit.custom_dimension_5::TEXT,
  matomo_log_visit.config_os_version::TEXT,
  matomo_log_visit.config_resolution::TEXT,
  matomo_log_visit.config_browser_name::TEXT,
  matomo_log_visit.config_browser_engine::TEXT,
  matomo_log_visit.config_device_brand::TEXT,
  matomo_log_visit.config_device_model::TEXT,
  matomo_log_visit.config_realplayer::BOOLEAN,
  matomo_log_visit.config_quicktime::BOOLEAN,
  matomo_log_visit.visitor_count_visits::INT,
  matomo_log_visit.visitor_seconds_since_first::INT,
  matomo_log_visit.visitor_seconds_since_order::INT,
  matomo_log_visit.user_id::TEXT,
  ENCODE(DECODE(matomo_log_visit.config_id,'base64'),'hex')::TEXT AS config_id, -- HEX type in mysql
  matomo_log_visit.config_os::TEXT,
  matomo_log_visit.config_pdf::BOOLEAN,
  matomo_log_visit.profilable::BOOLEAN,
  matomo_log_visit.config_java::BOOLEAN,
  matomo_log_visit.config_flash::BOOLEAN,
  matomo_log_visit.config_cookie::BOOLEAN,
  matomo_log_visit.last_idlink_va::BIGINT,
  matomo_log_visit.visit_goal_buyer::BOOLEAN,
  matomo_log_visit.visit_total_time::INT,
  TO_TIMESTAMP(LEFT(matomo_log_visit.visitor_localtime::text,-3)::int)::TIME AS visitor_localtime,
  matomo_log_visit.config_silverlight::BOOLEAN,
  matomo_log_visit.visit_total_events::INT,
  matomo_log_visit.config_windowsmedia::BOOLEAN,
  matomo_log_visit.visit_total_actions::INT,
  matomo_log_visit.visit_goal_converted::BOOLEAN,
  matomo_log_visit.visit_total_searches::SMALLINT,
  matomo_log_visit.location_browser_lang::TEXT,
  matomo_log_visit.config_browser_version::TEXT,
  matomo_log_visit.visit_entry_idaction_url::INT,
  matomo_log_visit.visit_exit_idaction_url::INT,
  matomo_log_visit.visit_entry_idaction_name::INT,
  matomo_log_visit.visit_exit_idaction_name::INT,
  matomo_log_visit.visit_total_interactions::INT,
  matomo_log_visit.visitor_seconds_since_last::INT

FROM matomo.matomo_log_conversion AS matomo_log_conversion
LEFT JOIN matomo.matomo_log_visit AS matomo_log_visit ON matomo_log_conversion.idvisit = matomo_log_visit.idvisit

WHERE matomo_log_conversion.idsite = '1'
AND matomo_log_conversion.location_country NOT IN ('xx','xx') --remove traffic from some countries
